2025-01-11 12:46:19,902 : INFO : root : Loading config.
2025-01-11 12:46:19,909 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-01-11 12:46:19,909 : INFO : ConfigProcessor : Loading config from cache: C:\Users\zackr\AppData\Local\Temp\0d11a866451559ccbc94cc0f149451f7.mpf_cache
2025-01-11 12:46:20,025 : INFO : ConfigProcessor : Loading config from cache: C:\Users\zackr\AppData\Local\Temp\294925c463dc5b459b9ed31f18ba4db4.mpf_cache
2025-01-11 12:46:20,027 : INFO : ConfigProcessor : Loading config from cache: C:\Users\zackr\AppData\Local\Temp\f3f38afaea8df340b072b5971b88038a.mpf_cache
2025-01-11 12:46:20,027 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev6
2025-01-11 12:46:20,027 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-01-11-12-46-19-mpf-ZR-laptop.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Custom-Pinball\\logs\\2025-01-11-12-46-19-mpf-ZR-laptop.log'}
2025-01-11 12:46:20,027 : INFO : Machine : MPF path: C:\Users\zackr\myenv\lib\site-packages\mpf
2025-01-11 12:46:20,027 : INFO : Machine : Machine path: C:\Custom-Pinball
2025-01-11 12:46:20,027 : INFO : Machine : Platform: win32
2025-01-11 12:46:20,027 : INFO : Machine : Python executable location: C:\Users\zackr\myenv\Scripts\python.exe
2025-01-11 12:46:20,028 : INFO : Machine : Python version: 3.9.13 (64-bit)
2025-01-11 12:46:20,031 : INFO : Machine : Initializing MPF...
2025-01-11 12:46:20,120 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,184 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-01-11 12:46:20,184 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,184 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev6, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,184 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,197 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,197 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,197 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,197 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,197 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,197 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Custom-Pinball\\logs\\2025-01-11-12-46-19-mpf-ZR-laptop.log', 'prev_value': None, 'change': True}
2025-01-11 12:46:20,197 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-01-11 12:46:20,211 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...our config.')>) at C:\Users\zackr\myenv\lib\site-packages\mpf\core\events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...our config.')>) at C:\Users\zackr\myenv\lib\site-packages\mpf\core\events.py:124>
Traceback (most recent call last):
  File "C:\Users\zackr\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\device_manager.py", line 88, in _load_device_modules
    self.load_devices_config(validate=True)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\device_manager.py", line 146, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 214, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 243, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_devices:bd_plunger:captures_from = "playfield" is not valid. Device "playfield" not found in "playfields:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-01-11 12:46:20,213 : INFO : Machine : Starting the main run loop with active modes: []
2025-01-11 12:46:20,214 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-01-11 12:46:20,214 : INFO : Machine : Shutting down...
2025-01-11 12:46:20,214 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-01-11 12:46:21,232 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "C:\Users\zackr\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\device_manager.py", line 88, in _load_device_modules
    self.load_devices_config(validate=True)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\device_manager.py", line 146, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 214, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 243, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "C:\Users\zackr\myenv\lib\site-packages\mpf\core\config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_devices:bd_plunger:captures_from = "playfield" is not valid. Device "playfield" not found in "playfields:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-01-11 12:46:31,116 : INFO : root : MPF run loop ended.
